### ISSUE TITLE
Errors when keys exist in compute_engine_known_hosts

### ISSUE THREAD

**Issue by Intelrunner** [GoogleCloudPlatform/deploystack-load-balanced-vms#1]
While attempting to install using posted instructions, I received several of these errors:

ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Existing host keys found in /home/eric/.ssh/google_compute_known_hosts
ssh: connect to host *********** port 22: Connection timed out

This is happening after the instance is launched, and after I get the message that 3 keys are being written to my hosts file. Then the app goes into an endless loop of the above.

**Comment by tpryan** [comment]
Thank so much for reporting this. I saw this issue during testing and thought I had resolved it. I'm completely away from a keyboard until Monday. I will look into ad soon as I can. Thanks for your patience. 

In the meantime, I know I had to jump through hoops to get the test version of it writing these properly... If you really want this before Monday you can temporarily rename your host vets file and try and see if that clears it up. I'm sorry to not have a better solution at my fingertips.

**Comment by tpryan** [comment]
The canonical fix for this seems to be: https://stackoverflow.com/questions/68354145/existing-host-keys-found-error-when-ssh-in-gcp-vm-instance

Delete the entries for the host of the same name as we are creating in this script.  Let me know if this doesn't work.
